---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull pradhyuman99/SPEminiproject

    - name: running container
      shell: docker run -it -d pradhyuman99/SPEminiproject/bin/bash
