---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell:sudo docker pull pradhyuman99/speminiproject

    - name: running container
      shell:sudo docker run -it -d pradhyuman99/speminiproject/bin/bash
