---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell:sudo docker pull maven-docker-project.jar

    - name: running container
      shell:sudo docker run -it -d maven-docker-project.jar /bin/bash
